 
name: CI
on:                                 
  push:
    branches:
    - main

jobs:
  main-to-gh-pages:
    runs-on: ubuntu-latest  

    steps:                          
      - name: Checkout gitbook
        uses: actions/checkout@v2

      - name: Install nodejs
        uses: actions/setup-node@v1

      - name: Configue gitbook
        run: |
          npm install -g gitbook-cli          
          gitbook install
          npm install -g gitbook-summary
                  
      - name: Generate _book folder
        run: |
          gitbook build
          cp SUMMARY.md _book
                  
      - name: push _book to branch main
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          REF: github.com/chgocn/notes.git
          MYEMAIL: chgocn@gmail.com                  
          MYNAME: chgocn          
        run: |
          cd _book
          git config --global user.email "${MYEMAIL}"
          git config --global user.name "${MYNAME}"
          git init
          git remote add origin https://${REF}
          git add . 
          git commit -m "🤖️sync $(date +%Y-%m-%d" "%H:%M:%S) With Build ${{github.run_number}} of ${{github.workflow}}"
          git branch -M main
          git push --force --quiet "https://${TOKEN}@${REF}" main:gh_pages